Use REST interface for AppVeyor
spekt/nunit.testlogger pull request #12
Opened 2017-08-06 07:17 UTC by ngbrown

The use of a blocking command-line tool per test is quite slow.  It caused my tests to be canceled at the 60 minute limit with only 2,559 completed.

The changes use a Async queue and HTTP batch POST to minimize the time impact on builds with a large number of tests.  With these changes, all 5,781 test complete in 19 minutes.

2017-08-11 10:09 UTC, Faizan2304 commented
@ngbrown : Thank you for your contribution 👍. I will take a look on this weekend.

2017-08-16 05:23 UTC, Faizan2304 requested changes
LGTM 👍 
Small changes required.

2017-08-16 05:23 UTC, Faizan2304 commented on src/Appveyor.TestLogger/AppveyorApiTests.cs
> +	internal class AppveyorApiTests
Do we need this class?

2017-08-16 05:23 UTC, Faizan2304 commented on src/Appveyor.TestLogger/AppveyorLogger.cs
> +	    private AppveyorLoggerQueue queue;
indentation

2017-08-16 05:23 UTC, Faizan2304 commented on src/Appveyor.TestLogger/AppveyorLogger.cs
> +		public void Initialize(TestLoggerEvents events, string testRunDirectory)
indentation

2017-08-16 05:23 UTC, Faizan2304 commented on src/Appveyor.TestLogger/AppveyorLogger.cs
> +			var testResult = new Dictionary<string, string>();
please fix the indentation of this file

2017-08-16 05:23 UTC, Faizan2304 commented on src/Appveyor.TestLogger/AppveyorLoggerQueue.cs
> +				consumeTask.Wait(TimeSpan.FromSeconds(10));
I was just wondering if there is any particular reason behind choosing 10 sec.

2017-08-16 06:45 UTC, ngbrown commented on src/Appveyor.TestLogger/AppveyorApiTests.cs
> +	internal class AppveyorApiTests
Not needed since I'm building JSON manually instead of using a library. - Removed.

2017-08-16 06:45 UTC, ngbrown commented on src/Appveyor.TestLogger/AppveyorLogger.cs
> +	    private AppveyorLoggerQueue queue;
I had accidentally added a mess of tab characters and spaces.  Added `.editorconfig` to enforce standardization.

2017-08-16 06:46 UTC, ngbrown commented on src/Appveyor.TestLogger/AppveyorLogger.cs
> +		public void Initialize(TestLoggerEvents events, string testRunDirectory)
fixed

2017-08-16 06:46 UTC, ngbrown commented on src/Appveyor.TestLogger/AppveyorLogger.cs
> +			var testResult = new Dictionary<string, string>();
fixed

2017-08-16 06:46 UTC, ngbrown commented on src/Appveyor.TestLogger/AppveyorLoggerQueue.cs
> +				consumeTask.Wait(TimeSpan.FromSeconds(10));
Not specifically.  The API calls are to a `localhost` and I expected them to be fast.  Just thought there should be something.  Do you have a suggestion for a better length?

2017-08-20 00:00 UTC, ngbrown commented
@Faizan2304 I found an issue with how I was handling the Aync at the `Flush` point.

I also fixed up the build script quite a bit to perform two-phase compilation so that the NuGet packages just built will be the ones tested.  The `TastResult.xml` or `loggerFile.xml` are deleted before test and then if they aren't created the AppVeyor build should fail.

I've re-based everything for a clean set of commits.

2017-09-17 14:54 UTC, Faizan2304 approved these changes

2017-09-17 14:54 UTC, merged